### ISSUE TITLE
sendgrid-mailer crashing on heroku

### ISSUE THREAD

**Issue by Ankiewicz** [adamreisnz/sendgrid-mailer#2]
Good Morning, Just trying to get the mailer to send, i have it working locally no issue, but as I push my application to Heroku, the app crashes on their side.

When running locally I am receiving emails just fine.

```var mailer = require('sendgrid-mailer').config(process.env.SENDGRID_API_KEY);```

```  const email = {
    to: 'myemailaddress@gmail.com',
    from: '<b@example.org>',
    subject: 'Hello world',
    text: 'Hello plain world!',
    html: '<p>Hello HTML world!</p>',
  };
```

`2017-01-25T19:45:31.150297+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-25T19:45:33.916021+00:00 app[web.1]: /app/node_modules/sendgrid-mailer/index.js:89
2017-01-25T19:45:33.916050+00:00 app[web.1]:       const [name, email] = splitNameEmail(identity);
2017-01-25T19:45:33.916064+00:00 app[web.1]:             ^
2017-01-25T19:45:33.916065+00:00 app[web.1]: 
2017-01-25T19:45:33.916065+00:00 app[web.1]: SyntaxError: Unexpected token [
2017-01-25T19:45:33.916067+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2017-01-25T19:45:33.916067+00:00 app[web.1]:     at Module._compile (module.js:413:25)
2017-01-25T19:45:33.916068+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2017-01-25T19:45:33.916068+00:00 app[web.1]:     at Module.load (module.js:355:32)
2017-01-25T19:45:33.916068+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2017-01-25T19:45:33.916069+00:00 app[web.1]:     at Module.require (module.js:365:17)
2017-01-25T19:45:33.916069+00:00 app[web.1]:     at require (module.js:384:17)
2017-01-25T19:45:33.916070+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/routes.js:7:14)
2017-01-25T19:45:33.916070+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2017-01-25T19:45:33.916071+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2017-01-25T19:45:34.025629+00:00 heroku[web.1]: Process exited with status 1
2017-01-25T19:45:34.038848+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by adamreisnz** [comment]
It looks like your node version might not support ES6 syntax. What version of Node are you running this on? Are you able to upgrade it to 6 or 7?

If not, I'll look into changing the syntax to support older versions of Node as well.

**Comment by Ankiewicz** [comment]
2017-02-01T06:12:06.537863+00:00 app[web.1]: /app/node_modules/sendgrid-mailer/index.js:89
2017-02-01T06:12:06.537881+00:00 app[web.1]:       const [name, email] = splitNameEmail(identity);
2017-02-01T06:12:06.537882+00:00 app[web.1]:             ^
2017-02-01T06:12:06.537882+00:00 app[web.1]: 
2017-02-01T06:12:06.537883+00:00 app[web.1]: SyntaxError: Unexpected token [
2017-02-01T06:12:06.537883+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2017-02-01T06:12:06.537884+00:00 app[web.1]:     at Module._compile (module.js:413:25)
2017-02-01T06:12:06.537885+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)
2017-02-01T06:12:06.537885+00:00 app[web.1]:     at Module.load (module.js:355:32)
2017-02-01T06:12:06.537886+00:00 app[web.1]:     at Function.Module._load (module.js:310:12)
2017-02-01T06:12:06.537886+00:00 app[web.1]:     at Module.require (module.js:365:17)
2017-02-01T06:12:06.537887+00:00 app[web.1]:     at require (module.js:384:17)
2017-02-01T06:12:06.537887+00:00 app[web.1]:     at Object.<anonymous> (/app/routes/routes.js:7:14)
2017-02-01T06:12:06.537888+00:00 app[web.1]:     at Module._compile (module.js:434:26)
2017-02-01T06:12:06.537889+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:452:10)

**Comment by Ankiewicz** [comment]
Updating Node worked perfectly. Thank you for that.
